import '../models/user_model.dart';
import '../models/flight_model.dart';
import '../models/duty_model.dart';
import '../models/crew_model.dart';
import '../models/document_model.dart';
import '../models/notification_model.dart';
import '../models/warning_violation_model.dart';
import '../models/dashboard_stats_model.dart';

/// Comprehensive mock aviation dataset for Crew Flyx.
class MockData {
  // Current Crew Member Profile
  static const UserModel currentUser = UserModel(
    id: 'USR-8940',
    username: 'captain.hayes',
    fullName: 'Capt. Alexander Hayes',
    employeeId: 'EMP-78210',
    designation: 'Senior Commander (A320/A321)',
    companyName: 'SkyWings Aero International',
    companyCode: 'SKY-AERO',
    baseAirport: 'DEL / VIDP (Indira Gandhi Int Airport)',
    licenseNumber: 'ATPL-908234-IN',
    licenseExpiry: '28 Nov 2028',
    medicalExpiry: '15 Oct 2026',
    email: 'alexander.hayes@skywings.aero',
    phone: '+91 98765 43210',
    totalFlightHours: 7420,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  );

  // Dashboard Stats
  static const DashboardStatsModel dashboardStats = DashboardStatsModel(
    totalFlights: 24,
    upcomingFlights: 6,
    completedFlights: 18,
    pendingDocuments: 3,
    warnings: 2,
    violations: 1,
    totalFlightHours: 84.5,
    monthlyDutyHours: 112.0,
    monthlyTrends: [
      MonthlyStatPoint(month: 'Mar', flights: 18, dutyHours: 88.0),
      MonthlyStatPoint(month: 'Apr', flights: 22, dutyHours: 96.5),
      MonthlyStatPoint(month: 'May', flights: 20, dutyHours: 92.0),
      MonthlyStatPoint(month: 'Jun', flights: 26, dutyHours: 118.0),
      MonthlyStatPoint(month: 'Jul', flights: 23, dutyHours: 104.5),
      MonthlyStatPoint(month: 'Aug', flights: 24, dutyHours: 112.0),
    ],
    flightStatusDistribution: [
      StatusDistributionPoint(status: 'On-Time', count: 19, percentage: 79.2),
      StatusDistributionPoint(status: 'Delayed', count: 3, percentage: 12.5),
      StatusDistributionPoint(status: 'Scheduled', count: 2, percentage: 8.3),
    ],
  );

  // Upcoming & Active Flights
  static final List<FlightModel> flights = [
    FlightModel(
      id: 'FL-101',
      flightNumber: 'CF-1024',
      departureAirport: 'VNS',
      departureCity: 'Varanasi (LBS Int Airport)',
      arrivalAirport: 'DEL',
      arrivalCity: 'New Delhi (IGI Airport)',
      departureTime: DateTime.now().add(const Duration(hours: 1, minutes: 45)),
      arrivalTime: DateTime.now().add(const Duration(hours: 3, minutes: 15)),
      aircraft: 'Airbus A320neo (VT-FLX)',
      gate: 'Gate 3A',
      terminal: 'T1',
      status: FlightStatus.scheduled,
      crewStatus: 'Reporting in 45 min',
      crewRole: CrewRole.commander,
      duration: '1h 30m',
      distanceKm: 680,
      captainName: 'Capt. Alexander Hayes',
      firstOfficerName: 'FO Rajiv Sharma',
    ),
    FlightModel(
      id: 'FL-102',
      flightNumber: 'CF-2088',
      departureAirport: 'DEL',
      departureCity: 'New Delhi',
      arrivalAirport: 'BOM',
      arrivalCity: 'Mumbai (CSMIA)',
      departureTime: DateTime.now().add(const Duration(hours: 6, minutes: 30)),
      arrivalTime: DateTime.now().add(const Duration(hours: 8, minutes: 45)),
      aircraft: 'Airbus A321neo (VT-FLY)',
      gate: 'Gate 14',
      terminal: 'T3',
      status: FlightStatus.scheduled,
      crewStatus: 'Roster Confirmed',
      crewRole: CrewRole.commander,
      duration: '2h 15m',
      distanceKm: 1150,
      captainName: 'Capt. Alexander Hayes',
      firstOfficerName: 'FO Ananya Iyer',
    ),
    FlightModel(
      id: 'FL-103',
      flightNumber: 'CF-3301',
      departureAirport: 'BOM',
      departureCity: 'Mumbai',
      arrivalAirport: 'BLR',
      arrivalCity: 'Bengaluru (KIA)',
      departureTime: DateTime.now().add(const Duration(days: 1, hours: 3)),
      arrivalTime: DateTime.now().add(const Duration(days: 1, hours: 4, minutes: 40)),
      aircraft: 'Airbus A320neo (VT-FLA)',
      gate: 'Gate 8',
      terminal: 'T2',
      status: FlightStatus.scheduled,
      crewStatus: 'Duty Briefing Pending',
      crewRole: CrewRole.commander,
      duration: '1h 40m',
      distanceKm: 840,
      captainName: 'Capt. Alexander Hayes',
      firstOfficerName: 'FO Vikram Mehta',
    ),
    FlightModel(
      id: 'FL-104',
      flightNumber: 'CF-4450',
      departureAirport: 'BLR',
      departureCity: 'Bengaluru',
      arrivalAirport: 'DXB',
      arrivalCity: 'Dubai International',
      departureTime: DateTime.now().add(const Duration(days: 2, hours: 5)),
      arrivalTime: DateTime.now().add(const Duration(days: 2, hours: 9, minutes: 15)),
      aircraft: 'Airbus A321LR (VT-INT)',
      gate: 'Gate 22B',
      terminal: 'T2',
      status: FlightStatus.scheduled,
      crewStatus: 'International Layover',
      crewRole: CrewRole.commander,
      duration: '4h 15m',
      distanceKm: 2700,
      captainName: 'Capt. Alexander Hayes',
      firstOfficerName: 'FO Rajesh Sen',
    ),
    FlightModel(
      id: 'FL-105',
      flightNumber: 'CF-0912',
      departureAirport: 'DEL',
      departureCity: 'New Delhi',
      arrivalAirport: 'GOI',
      arrivalCity: 'Goa (Dabolim)',
      departureTime: DateTime.now().subtract(const Duration(hours: 14)),
      arrivalTime: DateTime.now().subtract(const Duration(hours: 11, minutes: 30)),
      aircraft: 'Airbus A320neo (VT-FLB)',
      gate: 'Gate 11',
      terminal: 'T3',
      status: FlightStatus.arrived,
      crewStatus: 'Flight Log Submitted',
      crewRole: CrewRole.commander,
      duration: '2h 30m',
      distanceKm: 1510,
      captainName: 'Capt. Alexander Hayes',
      firstOfficerName: 'FO Rajiv Sharma',
    ),
  ];

  // Duty Roster
  static final List<DutyModel> duties = [
    DutyModel(
      id: 'DT-501',
      dutyDate: DateTime.now(),
      dutyType: DutyType.flightDuty,
      reportingTime: DateTime.now().add(const Duration(minutes: 45)),
      releaseTime: DateTime.now().add(const Duration(hours: 9)),
      flightNumber: 'CF-1024 / CF-2088',
      location: 'DEL Base - Briefing Room 4',
      status: DutyStatus.upcoming,
      dutyHours: 8.25,
      blockHours: 3.75,
      remarks: 'Sector pairing: VNS-DEL-BOM. Complies with DGCA FDTL.',
      isCheckedIn: false,
    ),
    DutyModel(
      id: 'DT-502',
      dutyDate: DateTime.now().add(const Duration(days: 1)),
      dutyType: DutyType.flightDuty,
      reportingTime: DateTime.now().add(const Duration(days: 1, hours: 2)),
      releaseTime: DateTime.now().add(const Duration(days: 1, hours: 8)),
      flightNumber: 'CF-3301',
      location: 'BOM Base',
      status: DutyStatus.upcoming,
      dutyHours: 6.0,
      blockHours: 1.66,
      remarks: 'Overnight layover at Mumbai Taj Santacruz.',
      isCheckedIn: false,
    ),
    DutyModel(
      id: 'DT-503',
      dutyDate: DateTime.now().add(const Duration(days: 2)),
      dutyType: DutyType.standby,
      reportingTime: DateTime.now().add(const Duration(days: 2, hours: 6)),
      releaseTime: DateTime.now().add(const Duration(days: 2, hours: 14)),
      flightNumber: null,
      location: 'DEL Airport Standby Lounge',
      status: DutyStatus.upcoming,
      dutyHours: 8.0,
      blockHours: 0.0,
      remarks: 'Airport Standby (ASBY) - A320 rating.',
      isCheckedIn: false,
    ),
    DutyModel(
      id: 'DT-504',
      dutyDate: DateTime.now().add(const Duration(days: 3)),
      dutyType: DutyType.restPeriod,
      reportingTime: DateTime.now().add(const Duration(days: 3)),
      releaseTime: DateTime.now().add(const Duration(days: 4)),
      flightNumber: null,
      location: 'Home Base (DEL)',
      status: DutyStatus.restMandatory,
      dutyHours: 0.0,
      blockHours: 0.0,
      remarks: 'Mandatory 36-hour weekly rest period.',
      isCheckedIn: false,
    ),
    DutyModel(
      id: 'DT-505',
      dutyDate: DateTime.now().add(const Duration(days: 5)),
      dutyType: DutyType.simulator,
      reportingTime: DateTime.now().add(const Duration(days: 5, hours: 9)),
      releaseTime: DateTime.now().add(const Duration(days: 5, hours: 14)),
      flightNumber: 'SIM-A320-PPC',
      location: 'CAE Flight Training Academy, Gurugram',
      status: DutyStatus.upcoming,
      dutyHours: 5.0,
      blockHours: 4.0,
      remarks: 'Pilot Proficiency Check (PPC) & Low Visibility CAT III Ops.',
      isCheckedIn: false,
    ),
  ];

  // Crew Roster
  static final List<CrewModel> crewMembers = [
    const CrewModel(
      id: 'CRW-01',
      name: 'Capt. Alexander Hayes',
      employeeId: 'EMP-78210',
      designation: CrewDesignation.captain,
      baseAirport: 'DEL',
      status: CrewStatus.onDuty,
      aircraftRating: 'A320 / A321 (TRE)',
      phone: '+91 98765 43210',
      email: 'alexander.hayes@skywings.aero',
      totalHours: 7420,
      assignedFlight: 'CF-1024',
    ),
    const CrewModel(
      id: 'CRW-02',
      name: 'FO Rajiv Sharma',
      employeeId: 'EMP-88192',
      designation: CrewDesignation.firstOfficer,
      baseAirport: 'DEL',
      status: CrewStatus.onDuty,
      aircraftRating: 'A320neo Type Rated',
      phone: '+91 98112 34567',
      email: 'rajiv.sharma@skywings.aero',
      totalHours: 2850,
      assignedFlight: 'CF-1024',
    ),
    const CrewModel(
      id: 'CRW-03',
      name: 'Sarah Jenkins',
      employeeId: 'EMP-90214',
      designation: CrewDesignation.leadCabinCrew,
      baseAirport: 'DEL',
      status: CrewStatus.onDuty,
      aircraftRating: 'Cabin Safety & First Aid L3',
      phone: '+91 97234 56789',
      email: 'sarah.jenkins@skywings.aero',
      totalHours: 4100,
      assignedFlight: 'CF-1024',
    ),
    const CrewModel(
      id: 'CRW-04',
      name: 'FO Ananya Iyer',
      employeeId: 'EMP-89301',
      designation: CrewDesignation.firstOfficer,
      baseAirport: 'BOM',
      status: CrewStatus.scheduled,
      aircraftRating: 'A320 / A321 Type Rated',
      phone: '+91 96345 67890',
      email: 'ananya.iyer@skywings.aero',
      totalHours: 3200,
      assignedFlight: 'CF-2088',
    ),
    const CrewModel(
      id: 'CRW-05',
      name: 'Capt. Siddharth Rao',
      employeeId: 'EMP-70144',
      designation: CrewDesignation.captain,
      baseAirport: 'BLR',
      status: CrewStatus.standby,
      aircraftRating: 'A320 / A321 / A330',
      phone: '+91 95456 78901',
      email: 'siddharth.rao@skywings.aero',
      totalHours: 9800,
      assignedFlight: 'Standby DEL',
    ),
    const CrewModel(
      id: 'CRW-06',
      name: 'Elena Rostova',
      employeeId: 'EMP-94520',
      designation: CrewDesignation.cabinCrew,
      baseAirport: 'DEL',
      status: CrewStatus.scheduled,
      aircraftRating: 'Cabin Service Specialist',
      phone: '+91 94567 89012',
      email: 'elena.rostova@skywings.aero',
      totalHours: 1950,
      assignedFlight: 'CF-2088',
    ),
    const CrewModel(
      id: 'CRW-07',
      name: 'Capt. Marcus Vance',
      employeeId: 'EMP-69210',
      designation: CrewDesignation.captain,
      baseAirport: 'BOM',
      status: CrewStatus.rest,
      aircraftRating: 'B737-MAX / A320',
      phone: '+91 93678 90123',
      email: 'marcus.vance@skywings.aero',
      totalHours: 11400,
      assignedFlight: 'Rest (Mandatory)',
    ),
  ];

  // Documents
  static final List<DocumentModel> documents = [
    DocumentModel(
      id: 'DOC-01',
      title: 'DGCA Class 1 Medical Certificate',
      fileName: 'DGCA_Class1_Medical_Hayes.pdf',
      fileFormat: 'PDF',
      fileSize: '2.4 MB',
      category: DocumentCategory.medical,
      uploadDate: DateTime(2025, 10, 15),
      expiryDate: DateTime(2026, 10, 15),
      status: DocumentStatus.valid,
      issuedBy: 'Air Force Medical Establishment (AFME), New Delhi',
      documentNumber: 'MED-2025-0982',
    ),
    DocumentModel(
      id: 'DOC-02',
      title: 'Airline Transport Pilot License (ATPL)',
      fileName: 'ATPL_License_AL_908234.pdf',
      fileFormat: 'PDF',
      fileSize: '3.1 MB',
      category: DocumentCategory.crew,
      uploadDate: DateTime(2023, 11, 28),
      expiryDate: DateTime(2028, 11, 28),
      status: DocumentStatus.valid,
      issuedBy: 'Directorate General of Civil Aviation',
      documentNumber: 'ATPL-908234-IN',
    ),
    DocumentModel(
      id: 'DOC-03',
      title: 'Monthly FDTL Duty Hours Summary (July 2026)',
      fileName: 'FDTL_Summary_July2026.pdf',
      fileFormat: 'PDF',
      fileSize: '1.1 MB',
      category: DocumentCategory.fdtl,
      uploadDate: DateTime(2026, 8, 1),
      expiryDate: null,
      status: DocumentStatus.pendingApproval,
      issuedBy: 'Crew Flyx Compliance Engine',
      documentNumber: 'FDTL-2026-07-092',
    ),
    DocumentModel(
      id: 'DOC-04',
      title: 'A320neo Type Rating & PPC Endorsement',
      fileName: 'A320neo_TypeRating_PPC.pdf',
      fileFormat: 'PDF',
      fileSize: '4.2 MB',
      category: DocumentCategory.training,
      uploadDate: DateTime(2025, 9, 10),
      expiryDate: DateTime(2026, 9, 10),
      status: DocumentStatus.expiringSoon,
      issuedBy: 'CAE Flight Training Academy',
      documentNumber: 'TR-A320-8841',
    ),
    DocumentModel(
      id: 'DOC-05',
      title: 'Flight Release & Dispatch Plan CF-1024',
      fileName: 'OFP_CF1024_VNS_DEL.pdf',
      fileFormat: 'PDF',
      fileSize: '5.8 MB',
      category: DocumentCategory.flight,
      uploadDate: DateTime.now().subtract(const Duration(hours: 2)),
      expiryDate: null,
      status: DocumentStatus.valid,
      issuedBy: 'Flight Operations Control Center (OCC)',
      documentNumber: 'OFP-CF1024-20260817',
    ),
    DocumentModel(
      id: 'DOC-06',
      title: 'Dangerous Goods Regulation (DGR) Cat-10',
      fileName: 'DGR_Certification_Hayes.pdf',
      fileFormat: 'PDF',
      fileSize: '1.8 MB',
      category: DocumentCategory.training,
      uploadDate: DateTime(2024, 6, 12),
      expiryDate: DateTime(2026, 6, 12),
      status: DocumentStatus.expired,
      issuedBy: 'IATA Aviation Training Center',
      documentNumber: 'IATA-DGR-7741',
    ),
  ];

  // Warnings and Violations
  static final List<WarningViolationModel> warningsAndViolations = [
    WarningViolationModel(
      id: 'WV-101',
      isViolation: false,
      title: 'Approaching 28-Day Flight Time Limit',
      type: 'FDTL Cumulative Hours',
      date: DateTime.now().subtract(const Duration(days: 1)),
      description: 'You have logged 88.5 hours in the past 28 days against the 100.0-hour ceiling. Next duty must remain within 11.5 flight hours.',
      severity: SeverityLevel.moderate,
      status: IssueStatus.open,
      flightNumber: 'CF-1024 Pairing',
      reportedBy: 'FDTL Automated Monitor',
      resolutionNotes: 'Rostering has adjusted upcoming sectors to prevent exceeding maximum duty limits.',
    ),
    WarningViolationModel(
      id: 'WV-102',
      isViolation: false,
      title: 'DGR Recurrent Training Renewal Due',
      type: 'Training Compliance',
      date: DateTime.now().subtract(const Duration(days: 3)),
      description: 'Dangerous Goods Regulation (Cat 10) certification expired on 12 Jun 2026. Schedule simulator/e-learning session before next international duty.',
      severity: SeverityLevel.minor,
      status: IssueStatus.underReview,
      flightNumber: 'Ground Training',
      reportedBy: 'Training Department',
      resolutionNotes: 'Assigned e-learning module in Crew Flyx portal.',
    ),
    WarningViolationModel(
      id: 'WV-201',
      isViolation: true,
      title: 'Late Reporting for Pre-Flight Briefing',
      type: 'SOP Operational Violation',
      date: DateTime.now().subtract(const Duration(days: 6)),
      description: 'Reported 18 minutes past required briefing time for sector CF-0912 at DEL Terminal 3 due to expressway traffic congestion.',
      severity: SeverityLevel.minor,
      status: IssueStatus.acknowledged,
      flightNumber: 'CF-0912',
      reportedBy: 'Chief Pilot Operations',
      resolutionNotes: 'Explanation received and acknowledged. Warning issued on crew record.',
    ),
  ];

  // Notifications
  static final List<NotificationModel> notifications = [
    NotificationModel(
      id: 'NOTIF-01',
      title: 'New Flight Schedule Assigned',
      description: 'You have been paired for CF-1024 (VNS → DEL) departing at 08:30 AM. Please review flight documents.',
      timestamp: DateTime.now().subtract(const Duration(minutes: 25)),
      type: NotificationType.flightSchedule,
      priority: NotificationPriority.high,
      isRead: false,
      actionRoute: '/flight_schedule',
    ),
    NotificationModel(
      id: 'NOTIF-02',
      title: 'Crew Duty Roster Updated',
      description: 'Standby duty for 19 Aug 2026 has been adjusted to Airport Standby from 06:00 to 14:00.',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      type: NotificationType.dutyUpdate,
      priority: NotificationPriority.medium,
      isRead: false,
      actionRoute: '/duty_schedule',
    ),
    NotificationModel(
      id: 'NOTIF-03',
      title: 'Document Approval Required',
      description: 'Monthly FDTL Duty Hours summary for July 2026 requires your digital sign-off.',
      timestamp: DateTime.now().subtract(const Duration(hours: 5)),
      type: NotificationType.documentApproval,
      priority: NotificationPriority.medium,
      isRead: false,
      actionRoute: '/documents',
    ),
    NotificationModel(
      id: 'NOTIF-04',
      title: 'FDTL Alert: Approaching 28-Day Limit',
      description: 'Logged 88.5 flight hours in the trailing 28 days. Please inspect warnings tab.',
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      type: NotificationType.warning,
      priority: NotificationPriority.high,
      isRead: true,
      actionRoute: '/warnings_violations',
    ),
    NotificationModel(
      id: 'NOTIF-05',
      title: 'Monsoon Operations Advisory (VIDP)',
      description: 'Low visibility & gusty wind procedures in effect across northern sectors. Check NOTAMs.',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      type: NotificationType.announcement,
      priority: NotificationPriority.low,
      isRead: true,
      actionRoute: '/dashboard',
    ),
  ];
}
